name: GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6.0.8
      - uses: actions/setup-node@v6
        with:
          node-version: 22.13.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_CLOUDBASE_ENV_ID: yunlefun-8g7ybcxc7345c490
          VITE_CLOUDBASE_REGION: ap-shanghai
          VITE_CLOUDBASE_ACCESS_KEY: ${{ secrets.CLOUDBASE_ACCESS_KEY }}
          VITE_GMM_COMMENTS_URL: https://apps.yunle.fun/app/give-me-money
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true
